### PR TITLE
Added Update Property Feature

### PR DESCRIPTION
**Pull request by ghost**
Added the aspects of the update property feature and updated the
properties POST request to support NULL tenant emails.

### CODE REVIEW

**Comment by nirrek** [comment]
https://github.com/nirrek/wallflyServer/blob/a16e3c8aa5f0581ec2a71f31ce07085b066ed0aa/handlers/propertyDetails.js#L126

If you look at `getTenantByEmail` `getOwnerByEmail` they are exactly the same except for a single character in the sql query. Rather than having all this duplicated code, make a single function `getUserByEmail(options, callback)` and specify a `userType` property in the options.

**Comment by nirrek** [comment]
Note that this is actually why you will see me make functions that take an `options` object, as you can add new properties after the fact (as is the case here), without having to change the function signature.

**Comment by nirrek** [comment]
### To be fixed.
- [x] Duplicated logic in `getTenantByEmail` and `getOwnerByEmail`
- [x] Remove unused arguments from the handler function definitions in `propertyDetails.js`.
- [x] Fix the SQL in the `getHandler()` to handle a NULL tenant. Test it works by updating a property by removing a tenant. Then checking details show up correctly in property list, and when re-editing the property details.

**Comment by ghost** [comment]
Should be good now let me know if it isn't. Should also be merged with master now.

**Comment by nirrek** [comment]
@jListo You haven't pushed any new commits. Note that commits show up in chronological order in the timeline above^^, so if you can't seem them there, then chances are all you have done is added new commits to your local repository.

**Pull request merged**
